### ISSUE TITLE
Make url work if you don't URL encode the + symbol

### ISSUE THREAD

**Issue by rsmith013** [cedadev/archive-opensearch#17]
At the moment, if you include the `httpAccept` parameter in your request you have to manually URL encode the `+` character. `+` becomes `%2B`.

See if there is a way that you could supply the response type using the `+` symbol so your parameter becomes `httpAccept=application/geo+json` instead of `httpAccept=application/geo%2Bjson`

**Comment by philipkershaw** [comment]
I don't think  you can do this with HTTP URIs.  However, clients can use '+' with HTTP header using content negotiation

**Comment by rsmith013** [comment]
> The characters ! $ & ' ( ) * + , ; = are permitted by generic URI syntax to be used unencoded in the user information, host, and path as delimiters.

I'll put it low on the priority list but might be worth 15mins just to check.

**Comment by philipkershaw** [comment]
Yes, RFC says:
`The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.`

... so you can do it but it's modifying the semantics a little.  Best method is content negotiation through the HTTP header IMOP.

**Comment by rsmith013** [comment]
ok, i'll close this then.
