### ISSUE TITLE
Add per-variable metadata, e.g. name, long name, units, dimension names, dimension sizes, dimension units

### ISSUE THREAD

**Issue by richdsmith** [cedadev/archive-opensearch#28]
Data types

**Comment by rsmith013** [comment]
Have added variables at the file level with some metadata. Work is progressing to provide variables via the ISO19115 export at CEDA catalogue datasets( FeatureCollections)

Variable dimensions and data types can be retrieved via the opendap endpoint so is the best source of this information.
